version: '3'
services: 
  meilisearch: 
    build: 
      context: .
      target: main
    ports:
      - "7700:7700"
    environment: 
      - MEILI_MASTER_KEY=meili-master-key
    volumes: 
      - ./meili_data:/meili_data