version: '3.7' 

services: 
  meili-dump:
    build: 
      context: .
    ports:
      - "9000:8080"
    environment: 
      - MEILI_MASTER_KEY=meili-master-key
      - MEILI_ENV=development
      - MEILI_LOG_LEVEL=DEBUG
    volumes: 
      - ./meili_data/data.ms:/tmp/data.ms 
      - ./meili_data/dumps:/usr/meili_dumps