version: '3.7' 

services: 
  search_engine:
    build: 
      context: ./search_engine 
      target: local 
    ports:
      - 7700:7700 
    volumes: 
      - ./data.ms:/data.ms 
      - ./dumps:/dumps