version: '3.7' 

services: 
  search_engine:
    build: 
      context: .
    ports:
      - "9000:8080"
    environment: 
      - MEILI_MASTER_KEY=f340cdc6ae3d4f65
      - MEILI_ENV=production
    volumes: 
      - ./meili_data:/var/task/meili_data/