version: '3.7' 

services: 
  search_engine:
    build: 
      context: .
    ports:
      - "9000:8080"
    #environment: 
      #- MEILI_MASTER_KEY=meili-master-key
      #- MEILI_ENV=development
    volumes: 
      - ./meili_data:/var/task/meili_data/