version: '3.7' 

services: 
  search_engine:
    build: 
      context: .
      target: local 
    ports:
      - 7700:7700 
    environment: 
      - MEILI_MASTER_KEY=meili-master-key
    volumes: 
      - ./meili_data:/meili_data