version: '3.7' 

services: 
  search_engine:
    build: 
      context: .
    ports:
      - "9000:8080"
    environment: 
      - MEILI_MASTER_KEY=meili-master-key
    volumes: 
      - ./meili_data:/meili_data